### PR TITLE
Add support for building with Mingw-gcc

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by 10110111** [comment]
What is the issue with external only TUs? I've never heard of it. Any link?

**Comment by hmartinez82** [comment]
It's a known issue and I'm still working on a solution. It's only a problem with clang. GCC does not have this issue :(
https://stackoverflow.com/questions/25050575/basic-use-of-c-archives-libraries-with-clang-linker

**Comment by hmartinez82** [comment]
So far I only got it locally building with clang if I remove the `extern` and convert it to a `static` and initialize its value in `config.h` instead of `version.cpp`

**Comment by 10110111** [comment]
> So far I only got it locally building with clang if I remove the `extern` and convert it to a `static` and initialize its value in `config.h` instead of `version.cpp`

Well this is not a good solution because it will force rebuilding of all sources from scratch on every commit (even CCache won't speed it up). Isolation of the change to a single file, `version.cpp`, was deliberate.

From your links I see that initializing the external definition helps the people with this problem. But here `PROJECT_VERSION` is already initialized, since it's a constant. Am I missing something?

**Comment by hmartinez82** [comment]
I forgot to add  "and removing its initialization from version.cpp"

**Comment by 10110111** [comment]
One relatively clean solution would be to turn this constant into a function: `const char* PROJECT_VERSION();`. Then `version.cpp` would contain the definition of this function, while `config.h` would declare it.

**Comment by hmartinez82** [comment]
Yes. I'm turning it into a function. After your comment about CCache, converting it into a function came to my mind

**Comment by hmartinez82** [comment]
I'm at a loss. Even after the conversion to a function above, now I'm getting:
```
[2/4] Linking CXX executable CalcMySky\calcmysky.exe
FAILED: CalcMySky/calcmysky.exe
cmd.exe /C "cd . && C:\msys64\clang64\bin\c++.exe -Werror=return-type -Wall -Wextra -fvisibility=hidden  CalcMySky/CMakeFiles/calcmysky.dir/calcmysky_autogen/mocs_compilation.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/main.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/util.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/glinit.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/cmdline.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/shaders.cpp.obj CalcMySky/CMakeFiles/calcmysky.dir/interpolation-guides.cpp.obj -o CalcMySky\calcmysky.exe -Wl,--out-implib,CalcMySky\libcalcmysky.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libversion.a  libcommon.a  C:/msys64/clang64/lib/libQt6OpenGL.dll.a  C:/msys64/clang64/lib/libQt6Widgets.dll.a  C:/msys64/clang64/lib/libQt6Gui.dll.a  C:/msys64/clang64/lib/libQt6Core.dll.a  -pthread  -lmpr  -luserenv  -ld3d11  -ldxgi  -ldxguid  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
ld.lld: error: undefined symbol: GetProjectVersion()
>>> referenced by CalcMySky/CMakeFiles/calcmysky.dir/main.cpp.obj:(main)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
[4/4] Linking CXX executable ShowMySky\showmysky.exe
FAILED: ShowMySky/showmysky.exe
cmd.exe /C "cd . && C:\msys64\clang64\bin\c++.exe -Werror=return-type -Wall -Wextra -fvisibility=hidden  ShowMySky/CMakeFiles/showmysky-cmd.dir/showmysky-cmd_autogen/mocs_compilation.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/qrc_resources.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/win32res.rc.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/main.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/util.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/GLWidget.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/MainWindow.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/ToolsWidget.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/Manipulator.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/RadiancePlot.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/DockScrollArea.cpp.obj ShowMySky/CMakeFiles/showmysky-cmd.dir/GLSLCosineQualityChecker.cpp.obj -o ShowMySky\showmysky.exe -Wl,--out-implib,ShowMySky\libshowmysky.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libversion.a  libcommon.a  C:/msys64/clang64/lib/libQt6OpenGLWidgets.dll.a  C:/msys64/clang64/lib/libQt6Widgets.dll.a  C:/msys64/clang64/lib/libQt6OpenGL.dll.a  C:/msys64/clang64/lib/libQt6Gui.dll.a  C:/msys64/clang64/lib/libQt6Core.dll.a  -pthread  -lmpr  -luserenv  -ld3d11  -ldxgi  -ldxguid  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
ld.lld: error: undefined symbol: GetProjectVersion()
```
But only with clang! gcc and msvc ware linking correctly, grr

**Comment by 10110111** [comment]
> Even after the conversion to a function above, now I'm getting

What if you avoid `-fvisibility=hidden`?

**Comment by hmartinez82** [comment]
Same thing, removing `-fvisibility=hidden` was the very first thing I tried 😢

**Comment by 10110111** [comment]
Interestingly, I experience no problem whatsoever when building with clang 10.0.0-4ubuntu1 on Ubuntu 20.04, even with the current `master`.

**Comment by hmartinez82** [comment]
I'm using 17.0.1 from MSYS2

**Comment by 10110111** [comment]
Well, what if you populate `clang_dummy` with the code to return the pointer, and call it instead of `PROJECT_VERSION` in the places of use? It seems strange that a simple renaming (and a change of return type) leads to a problem.

**Comment by hmartinez82** [comment]
I already did that, (well, not called clang_dymmy). you'll have to refresh this PR

**Comment by 10110111** [comment]
> I already did that, (well, not called clang_dymmy). you'll have to refresh this PR

No, I mean, your `clang_dummy`, IIUC, fixed the problem. But now the `GetProjectVersion` reintroduces it. So I suggest trying to go from the working direction, checking what exact change reintroduces the problem.

**Comment by hmartinez82** [comment]
The original PR was also failing with the `clang_dummy()` call

**Comment by hmartinez82** [comment]
Ok. I've changed the title. Let's chew one thing at a time. I'll start working on the MSYS2 recipe for this project. INDIlib is next.

**Comment by hmartinez82** [comment]
Here we go https://github.com/msys2/MINGW-packages/pull/18697

**Comment by hmartinez82** [comment]
@10110111 where can I download .atmo files to test ShowMySky.exe ?

**Comment by 10110111** [comment]
`examples/sample.atmo`

**Comment by 10110111** [comment]
Ah, wait, it's for CalcMySky. For ShowMySky you can download the earth atmosphere model in the release assets list.

**Comment by 10110111** [comment]
@hmartinez82 You might not have received my email, but I need your reply. Here's a copy of the message:

It appears that CalcMySky, being licensed under the GPLv3, is
incompatible with Stellarium that's under GPLv2. So I'm going to
relicense CalcMySky under GPLv2. As you all have contributed to the
project, I need your permission to relicense it, or I may have to
remove your contribution.

So, are you OK with relicensing CalcMySky from GPLv3 to GPLv2?

**Comment by hmartinez82** [comment]
Yes. I am 😊

**Pull request merged**
