### PR TITLE
Use -fPIC flag in Linux

### LINKED ISSUE #21: Failing building CalcMySky
According to https://www.linux.org.ru/news/opensource/17737893 CalcMySky can't be building on Devuan/Ceres by GCC 14 without `-fPIC` option.

### PR DESCRIPTION
**Pull request by data-man**
Fixes #21.

It was my issue on LOR.

### CODE REVIEW

**Comment by 10110111** [comment]
What is the error message that this PR is supposed to fix?

**Comment by data-man** [comment]
With `-DQT_VERSION=6` option.
```
[39/61] Linking CXX shared library ShowMySky/libShowMySky-Qt6.so.15.0.0
FAILED: ShowMySky/libShowMySky-Qt6.so.15.0.0
: && /usr/bin/c++ -fPIC -Werror=return-type -Wall -Wextra -fvisibility=hidden  -O3 -DNDEBUG   -shared -Wl,-soname,libShowMySky-Qt6.so.15 -o ShowMySky/libShowMySky-Qt6.so.15.0.0 ShowMySky/CMakeFiles/ShowMySky.dir/ShowMySky_autogen/mocs_compilation.cpp.o ShowMySky/CMakeFiles/ShowMySky.dir/api/AtmosphereRenderer.cpp.o ShowMySky/CMakeFiles/ShowMySky.dir/AtmosphereRenderer.cpp.o ShowMySky/CMakeFiles/ShowMySky.dir/util.cpp.o  libversion.a  libcommon.a  /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so.6.6.2  /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6.6.2  /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6.6.2  /usr/lib/x86_64-linux-gnu/libQt6Core.so.6.6.2  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so && :
/usr/bin/ld: libcommon.a(Spectrum.cpp.o): warning: relocation against `_ZTISt12out_of_range@@GLIBCXX_3.4' in read-only section `.text.unlikely'
/usr/bin/ld: libcommon.a(EclipsedDoubleScatteringPrecomputer.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt12out_of_range@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
[40/61] Building CXX object ShowMySky/CMakeFiles/showmysky-cmd.dir/showmysky-cmd_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
Command exited with non-zero status 1
```
Also `#include <cassert>` is missed.

**Comment by 10110111** [comment]
Is the following patch instead of yours (barring the `<cassert>` addition) sufficient?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9d66ae6..adaed3b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,7 @@ set(CMAKE_FIND_USE_PACKAGE_REGISTRY false)
 
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED ON)
+set(CMAKE_POSITION_INDEPENDENT_CODE ON)
 if(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU|Clang")
     set(CMAKE_CXX_FLAGS "-Werror=return-type -Wall -Wextra -fvisibility=hidden ${CMAKE_CXX_FLAGS}")
 endif()
```

**Comment by data-man** [comment]
> Is the following patch instead of yours (barring the `<cassert>` addition) sufficient?

Yes.

**Comment by 10110111** [comment]
Superseded by d3aa2037093f45cc0f39c7ef07927252a3d754f1.

**Pull request closed without merging**
